// ─────────────────────────────────────────────────────────────────────────────
// Web Development Project — Assignment Sheet
// ─────────────────────────────────────────────────────────────────────────────

#let course = "Computer Science"
#let level  = "Gymnasium Muttenz"
#let term   = "2026-27"
#let sheet-type = "Project Assignment"

// ── Page setup ────────────────────────────────────────────────────────────────
#set page(
  paper: "a4",
  margin: (top: 2.8cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
  header: context {
    set text(size: 9pt, fill: rgb("#999999"))
    grid(
      columns: (1fr, 1fr),
      align(left,  [#sheet-type — Web Development]),
      align(right, [#course — #level]),
    )
    line(length: 100%, stroke: 0.4pt + rgb("#999999"))
  },
  footer: context {
    set text(size: 9pt, fill: rgb("#999999"))
    align(center, counter(page).display("1"))
  },
)

// ── Heading styles ────────────────────────────────────────────────────────────
#show heading.where(level: 1): it => block(breakable: false)[
  #v(1.2em)
  #text(size: 11pt, weight: "bold", fill: rgb("#111111"), upper(it.body))
  #v(0.15em)
  #line(length: 100%, stroke: 1pt + rgb("#2E6DA4"))
  #v(0.5em)
]

#show heading.where(level: 2): it => {
  v(0.6em)
  text(size: 11pt, weight: "bold", fill: rgb("#111111"), it.body)
  v(0.2em)
}

// ── Import shared styles and components ───────────────────────────────────────
#import "../cs-style.typ": *

// ── Title block ───────────────────────────────────────────────────────────────
#{
  text(size: 20pt, weight: "bold", fill: primary)[Build Your Own Website]
  v(0.05em)
  text(size: 12pt, fill: muted)[Web Development Project #sym.dot.c #course #sym.bar.v #level #sym.bar.v #term]
  v(0.3em)
  line(length: 100%, stroke: 1pt + accent)
  v(0.8em)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTENT
// ─────────────────────────────────────────────────────────────────────────────

= Overview

In this project you will design and build a small website on a topic of
your own choosing. You will work with the three core technologies of the
web — HTML, CSS, and JavaScript — each in its own file, just as
professional developers do.

The goal is not only to produce a working website, but to practice the
skill of teaching yourself something new: researching independently, using
tools such as AI assistants or online resources, and genuinely
understanding and owning the code you write.

#warnbox(
  "⚠ Read this before you start",
  [This project is graded very differently from a typical assignment.
   *Understanding your own code matters more than how much of it you
   write.* A simple site you can explain completely will score higher
   than an impressive one you cannot. Section 6 explains exactly how
   this works — read it now, not after you have finished building.],
)

== GitHub Classroom

You will receive a starter repository through GitHub Classroom containing
three (mostly) empty files: `index.html`, `style.css`, and `script.js`.
All your work must remain in — or be linked from — these files.

== Learning Goals

#checklist(
  [Apply HTML, CSS, and JavaScript to create a structured, styled, and interactive webpage.],
  [Learn new techniques independently and document your learning process honestly.],
  [Use Git in a professional, granular way so your development history tells a clear story.],
  [Critically evaluate and adapt code found online or generated by AI rather than copying it blindly.],
  [Communicate technical decisions clearly and confidently in an oral Technical Discussion.],
)

= Before You Write Any Code: Planning

Before touching `index.html`, complete the *Project Planning Worksheet*
(distributed separately). It asks you to:

#steps(
  [Brainstorm at least three different ideas for your site's topic —
   not three variations on one idea.],
  [Choose one, and explain why you chose it over the others.],
  [Write down your planned features, sorted into #tier-core,
   #tier-extension, and #tier-challenge.],
  [Sketch a rough week-by-week timeline for the project.],
)

Push this worksheet — or a summary of it in `README.md` — as one of your
*first commits*. This is not a formality: the Planning grade depends on
your plan existing *before* you started building, which is checked
against your commit timestamps.

You will return to this worksheet at the *end* of the project to write a
short retrospective comparing what you built to what you planned.

= Technical Requirements

== File structure

#checklist(
  [All HTML lives in `index.html`; all CSS in `style.css`; all JavaScript in `script.js`.],
  [No inline styles (`style="..."` attributes) and no `<script>` or `<style>` blocks inside `index.html`.],
  [The three files are correctly linked to each other.],
)

== HTML

#checklist(
  [At least 10 different HTML tags used correctly and meaningfully
   (e.g. headings, paragraphs, lists, links, images, forms, tables — see
   the lesson notes for the full set covered in class).],
  [A valid document structure: `<!DOCTYPE html>`, `<html>`, `<head>`
   (with `<meta charset>` and `<title>`), and `<body>`.],
)

== CSS

#checklist(
  [At least 5 different CSS properties used correctly and purposefully.],
  [Selectors target your own elements meaningfully — no unused rules.],
)

== JavaScript

#checklist(
  [At least one piece of real interactivity (e.g. a button that changes
   content, a simple check, an animation trigger).],
  [You understand and can explain every line, including anything
   originally suggested by an AI.],
)

#infobox(
  "Meeting the minimums is enough",
  [These numbers are a *floor*, not a target to exceed. A site that meets
   every requirement cleanly, with content you fully understand, scores
   *at least as well* as a more elaborate one — there is no bonus for
   sheer quantity of code. Depth of understanding is what is rewarded,
   not scope.],
)

= Documenting Your Learning

== Git commits

#checklist(
  [Commit frequently and in small, logical steps. Each message describes
   what changed and why.],
  [Your commit history shows a visible progression from first idea to
   finished site.],
  [Single large "dump" commits are penalized.],
)

== The three required learning-log entries

Maintain a file called `JOURNAL.md` in your repository. You are free to
add as many entries as you like, but *at least three are required — one
for HTML, one for CSS, and one for JavaScript.* Tag each entry clearly
with its language, for example:

```
## [CSS] Rounding the corners of my image gallery
```

Each of the three tagged entries must contain all four parts:

#steps(
  [*What you were trying to do.*],
  [*Where you found help* (AI tool, website, friend, parent, teacher, ...).],
  [*What you learned or understood* from that source.],
  [*How you adapted the idea* to fit your specific project — never
   paste-and-forget.],
)

#warnbox(
  "⚠ This is checked entry by entry",
  [A missing tag, or an entry that skips one of the four parts, is
   treated as that entry not existing. Three complete, honest entries —
   one per language — are worth far more to your grade than ten vague
   ones.],
)

= AI & External Code Policy

You may use AI assistants, Stack Overflow, tutorials, and similar
resources as learning tools. You may *not* copy code directly without
understanding it. Any code you include must be analyzed and adapted to
your own project's needs.

#warnbox(
  "⚠ You will be asked to explain any part of your code",
  [This includes code that was originally suggested by an AI. If you
   cannot explain why a line is there or what it does, it will cost you
   far more in the Oral Defense than it would have cost to leave it out.],
)

= Oral Defense

At the end of the project there will be a short individual oral
examination — the *Technical Discussion*. You should be prepared to:

#checklist(
  [Walk through your website and explain the structure of your code.],
  [Explain why you made specific technical or design choices.],
  [Clarify how a particular code block works, including complex sections.],
  [Describe one thing you struggled with and how you resolved it —
   this is a good moment to revisit Part C of your planning worksheet.],
)

#warnbox(
  "⚠ Read this carefully — it changes how you should approach this project",
  [Unlike a typical rubric where every section simply adds points, *your
   Oral Defense score acts as a multiplier on your entire project grade.*
   A technically excellent website paired with a defense where you cannot
   explain your own code will *not* receive a passing grade — no matter
   how good the rest of your submission looks. \
   \
   The reverse is also true: a simple, modest project that you understand
   completely and can discuss confidently will outscore a complex one you
   cannot explain. \
   \
   The full mechanism, with worked examples, is in the grading rubric
   handed out alongside this sheet. Read it before you start building —
   it should genuinely change how much code you take from elsewhere
   without fully understanding it first.],
)

= Suggested Timeline

#table(
  columns: (5em, 1fr),
  stroke: none,
  fill: (_, row) => if row == 0 { rgb("#111111") } else if calc.odd(row) { light } else { white },
  inset: 8pt,
  table.header(
    text(size: 9pt, weight: "bold", fill: white)[Week],
    text(size: 9pt, weight: "bold", fill: white)[Focus],
  ),
  [1], [Brainstorm and plan (worksheet Parts A + B). Choose your topic.
        Sketch a rough layout on paper. First commit: a basic
        `index.html` skeleton plus your plan.],
  [2], [Build the HTML structure; add content; commit regularly.],
  [3], [Style with CSS; experiment; commit each significant visual change.],
  [4], [Add JavaScript interactivity; write your three tagged
        `JOURNAL.md` entries as you go — not all at the end.],
  [5], [Polish, test in a fresh clone, complete Part C of your worksheet
        (retrospective), review your commit history, prepare for the
        Technical Discussion.],
)

Exact deadlines will be announced separately.

= What to Submit

#checklist(
  [Your project repository, pushed to GitHub, submitted via GitHub Classroom.],
  [Your completed Project Planning & Retrospective Worksheet (Parts A, B, and C).],
  [A `JOURNAL.md` with at least the three required tagged entries.],
)
